# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/MahmoudHc/Desktop/temp/riky/riky.srcs/sources_1/bd/design_2/ip/design_2_ri5cy_axi_wrapper_0_2/design_2_ri5cy_axi_wrapper_0_2.xci
# IP: The module: 'design_2_ri5cy_axi_wrapper_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/MahmoudHc/Desktop/temp/riky/riky.gen/sources_1/bd/design_2/ip/design_2_ri5cy_axi_wrapper_0_2/src/constrs.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_ri5cy_axi_wrapper_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/MahmoudHc/Desktop/temp/riky/riky.srcs/sources_1/bd/design_2/ip/design_2_ri5cy_axi_wrapper_0_2/design_2_ri5cy_axi_wrapper_0_2.xci
# IP: The module: 'design_2_ri5cy_axi_wrapper_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/MahmoudHc/Desktop/temp/riky/riky.gen/sources_1/bd/design_2/ip/design_2_ri5cy_axi_wrapper_0_2/src/constrs.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_ri5cy_axi_wrapper_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
