# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_0/design_2_system_ila_0_0.xci
# IP: The module: 'design_2_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/bd_074c.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c || ORIG_REF_NAME==bd_074c} -quiet] -quiet

# IP: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_0/bd_074c_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c_ila_lib_0 || ORIG_REF_NAME==bd_074c_ila_lib_0} -quiet] -quiet

# IP: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_1/bd_074c_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c_g_inst_0 || ORIG_REF_NAME==bd_074c_g_inst_0} -quiet] -quiet

# IP: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_2/bd_074c_slot_0_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c_slot_0_aw_0 || ORIG_REF_NAME==bd_074c_slot_0_aw_0} -quiet] -quiet

# IP: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_3/bd_074c_slot_0_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c_slot_0_w_0 || ORIG_REF_NAME==bd_074c_slot_0_w_0} -quiet] -quiet

# IP: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_4/bd_074c_slot_0_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c_slot_0_b_0 || ORIG_REF_NAME==bd_074c_slot_0_b_0} -quiet] -quiet

# IP: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_5/bd_074c_slot_0_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c_slot_0_ar_0 || ORIG_REF_NAME==bd_074c_slot_0_ar_0} -quiet] -quiet

# IP: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_6/bd_074c_slot_0_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c_slot_0_r_0 || ORIG_REF_NAME==bd_074c_slot_0_r_0} -quiet] -quiet

# XDC: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_074c_ila_lib_0 || ORIG_REF_NAME==bd_074c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_074c_ila_lib_0 || ORIG_REF_NAME==bd_074c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_0/bd_074c_ila_lib_0_ooc.xdc

# XDC: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/bd_074c_ooc.xdc

# XDC: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/design_2_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_0/design_2_system_ila_0_0.xci
# IP: The module: 'design_2_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/bd_074c.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c || ORIG_REF_NAME==bd_074c} -quiet] -quiet

# IP: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_0/bd_074c_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c_ila_lib_0 || ORIG_REF_NAME==bd_074c_ila_lib_0} -quiet] -quiet

# IP: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_1/bd_074c_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c_g_inst_0 || ORIG_REF_NAME==bd_074c_g_inst_0} -quiet] -quiet

# IP: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_2/bd_074c_slot_0_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c_slot_0_aw_0 || ORIG_REF_NAME==bd_074c_slot_0_aw_0} -quiet] -quiet

# IP: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_3/bd_074c_slot_0_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c_slot_0_w_0 || ORIG_REF_NAME==bd_074c_slot_0_w_0} -quiet] -quiet

# IP: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_4/bd_074c_slot_0_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c_slot_0_b_0 || ORIG_REF_NAME==bd_074c_slot_0_b_0} -quiet] -quiet

# IP: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_5/bd_074c_slot_0_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c_slot_0_ar_0 || ORIG_REF_NAME==bd_074c_slot_0_ar_0} -quiet] -quiet

# IP: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_6/bd_074c_slot_0_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_074c_slot_0_r_0 || ORIG_REF_NAME==bd_074c_slot_0_r_0} -quiet] -quiet

# XDC: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_074c_ila_lib_0 || ORIG_REF_NAME==bd_074c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_074c_ila_lib_0 || ORIG_REF_NAME==bd_074c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/ip/ip_0/bd_074c_ila_lib_0_ooc.xdc

# XDC: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/bd_0/bd_074c_ooc.xdc

# XDC: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_system_ila_0_0/design_2_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
