# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const.xdc

# Block Designs: bd/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_microblaze_riscv_0_1/design_2_microblaze_riscv_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_microblaze_riscv_0_1 || ORIG_REF_NAME==design_2_microblaze_riscv_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_dlmb_v10_1/design_2_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_dlmb_v10_1 || ORIG_REF_NAME==design_2_dlmb_v10_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ilmb_v10_1/design_2_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ilmb_v10_1 || ORIG_REF_NAME==design_2_ilmb_v10_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_dlmb_bram_if_cntlr_1/design_2_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==design_2_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ilmb_bram_if_cntlr_1/design_2_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==design_2_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_lmb_bram_1/design_2_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_lmb_bram_1 || ORIG_REF_NAME==design_2_lmb_bram_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_microblaze_riscv_0_axi_periph_upgraded_ipi_imp_xbar_0/design_2_microblaze_riscv_0_axi_periph_upgraded_ipi_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_microblaze_riscv_0_axi_periph_upgraded_ipi_imp_xbar_0 || ORIG_REF_NAME==design_2_microblaze_riscv_0_axi_periph_upgraded_ipi_imp_xbar_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_microblaze_riscv_0_axi_periph_1/design_2_microblaze_riscv_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_microblaze_riscv_0_axi_periph_1 || ORIG_REF_NAME==design_2_microblaze_riscv_0_axi_periph_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_microblaze_riscv_0_axi_intc_1/design_2_microblaze_riscv_0_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_microblaze_riscv_0_axi_intc_1 || ORIG_REF_NAME==design_2_microblaze_riscv_0_axi_intc_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_microblaze_riscv_0_xlconcat_1/design_2_microblaze_riscv_0_xlconcat_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_microblaze_riscv_0_xlconcat_1 || ORIG_REF_NAME==design_2_microblaze_riscv_0_xlconcat_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_mdm_1_1/design_2_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_mdm_1_1 || ORIG_REF_NAME==design_2_mdm_1_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_clk_wiz_1_100M_0/design_2_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_2_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_system_ila_0_0/design_2_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_system_ila_0_0 || ORIG_REF_NAME==design_2_system_ila_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_0_1/design_2_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_0_1 || ORIG_REF_NAME==design_2_axi_gpio_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_clk_wiz_0_2/design_2_clk_wiz_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_2 || ORIG_REF_NAME==design_2_clk_wiz_0_2} -quiet] -quiet

# XDC: c:/Users/MahmoudHc/Desktop/ptech/Projet/project_1/project_1.gen/sources_1/bd/design_2/design_2_ooc.xdc
