# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/project_1/const.xdc

# Block Designs: bd/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_bram_ctrl_0_0/design_2_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_2_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_bram_ctrl_0_bram_0/design_2_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==design_2_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_bram_ctrl_1_0/design_2_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_bram_ctrl_1_0 || ORIG_REF_NAME==design_2_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_bram_ctrl_1_bram_0/design_2_axi_bram_ctrl_1_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_bram_ctrl_1_bram_0 || ORIG_REF_NAME==design_2_axi_bram_ctrl_1_bram_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_0_0 || ORIG_REF_NAME==design_2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_smc_0/design_2_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_smc_0 || ORIG_REF_NAME==design_2_axi_smc_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_processing_system7_0_1/design_2_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_processing_system7_0_1 || ORIG_REF_NAME==design_2_processing_system7_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_ps7_0_100M_0/design_2_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_2_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_0_0/design_2_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_0_0 || ORIG_REF_NAME==design_2_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_1_0/design_2_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_1_0 || ORIG_REF_NAME==design_2_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_2_0/design_2_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_2_0 || ORIG_REF_NAME==design_2_xlconstant_2_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_3_0/design_2_xlconstant_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_3_0 || ORIG_REF_NAME==design_2_xlconstant_3_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_4_0/design_2_xlconstant_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_4_0 || ORIG_REF_NAME==design_2_xlconstant_4_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ri5cy_axi_wrapper_0_1/design_2_ri5cy_axi_wrapper_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ri5cy_axi_wrapper_0_1 || ORIG_REF_NAME==design_2_ri5cy_axi_wrapper_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ri5cy_axi_wrapper_0_2/design_2_ri5cy_axi_wrapper_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ri5cy_axi_wrapper_0_2 || ORIG_REF_NAME==design_2_ri5cy_axi_wrapper_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_2_1/design_2_xlconstant_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconstant_2_1 || ORIG_REF_NAME==design_2_xlconstant_2_1} -quiet] -quiet

# XDC: c:/Users/MahmoudHc/Desktop/temp/riky/riky.gen/sources_1/bd/design_2/design_2_ooc.xdc
